"""removed id_ column in user_role

Revision ID: 211432aca61b
Revises: 845a729e9765
Create Date: 2025-05-09 07:05:05.369142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211432aca61b'
down_revision = '845a729e9765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
