"""add escrow

Revision ID: 845a729e9765
Revises: 92add47794ba
Create Date: 2025-05-08 18:04:58.842650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845a729e9765'
down_revision = '92add47794ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escrows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('is_released', sa.Boolean(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('dispute_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('escrows')
    # ### end Alembic commands ###
